# Generated by Django 2.2.24 on 2022-03-29 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Project Name')),
                ('description', models.TextField(max_length=250, verbose_name='Project Description')),
                ('developers', models.ForeignKey(limit_choices_to={'designation': 'dev'}, on_delete=django.db.models.deletion.PROTECT, related_name='dev', to='userprofile.Profile')),
                ('qaes', models.ForeignKey(limit_choices_to={'designation': 'qae'}, on_delete=django.db.models.deletion.PROTECT, related_name='qae', to='userprofile.Profile')),
            ],
        ),
    ]
