# Generated by Django 2.2.24 on 2022-03-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='developers',
        ),
        migrations.RemoveField(
            model_name='project',
            name='qaes',
        ),
    ]
