# Generated by Django 2.2.24 on 2022-04-04 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0002_auto_20220329_0813'),
        ('userprofile', '0003_auto_20220404_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Bug ID')),
                ('title', models.CharField(max_length=100, verbose_name='Bug Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Describe bug/feature in a paragraph')),
                ('deadline', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Bug Deadline')),
                ('type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], default='bug', max_length=20, verbose_name='Is it a Feature or Bug')),
                ('status', models.CharField(choices=[('start', 'New'), ('in_progress', 'Started'), ('completed', 'Resolved')], default='New', max_length=20, verbose_name='Bug/Feature Status')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bugs_imgs')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'designation': 'developer'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='developer_assigned', to='userprofile.Profile', verbose_name='Developer Assigned To')),
                ('creator', models.ForeignKey(limit_choices_to={'designation': 'qaengineer'}, on_delete=django.db.models.deletion.PROTECT, related_name='creator_qae', to='userprofile.Profile', verbose_name='Creator of Bug/Feature')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Found In Project')),
            ],
        ),
    ]
