# Generated by Django 2.2.24 on 2022-04-04 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='id',
        ),
        migrations.AlterField(
            model_name='bug',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Bug ID'),
        ),
    ]
