# Generated by Django 2.2.24 on 2022-04-07 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220329_0813'),
        ('bugs', '0003_auto_20220407_0417'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bug',
            unique_together={('project', 'title')},
        ),
    ]
